FROM php:8.3-fpm-alpine3.22

RUN apk update && apk upgrade --no-cache \
    && apk add --no-cache mariadb-connector-c-dev bash git unzip libxml2-utils \
    && docker-php-ext-install pdo pdo_mysql \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /app

COPY composer.json composer.lock ./

RUN composer install --no-interaction --prefer-dist --optimize-autoloader

COPY ./src ./src
COPY ./public ./public

WORKDIR /app
